### ISSUE TITLE
Process resource exhausted if receiving an MRCP message split into multiple parts

### ISSUE THREAD

**Issue by jsau-** [MayamaTakeshi/mrcp#5]
Apologies if I'm missing anything obvious - far from an expert here.

---

Reproduction details:

* Package version: 1.4.0
* Node version(s): 16.13.2 / 20.11.0
* Reproduced on: 2024-10-25

---

I'm using this library to handle connection to a [`unimrcp`](https://github.com/unispeech/unimrcp) server. [`unimrcp`](https://github.com/unispeech/unimrcp) has a buffer size for transmitted messages, and seems to split them if the total length of the message exceeds the buffer size (e.g. if the tx buffer size is `1024` bytes and we try to send a message that would be `1561` bytes total) it seems to send two individual messages. 

An example of some logs from [`unimrcp`](https://github.com/unispeech/unimrcp) can be seen below.
(_N.B. that `Content-Length` won't match exactly as I've anonymized some content denoted by `[omitted]`_):

```text/plain
2024-10-25 14:02:10:712771 [INFO]   Send MRCPv2 Data [omitted]:[omitted] <-> [omitted]:[omitted] [1022 bytes]
MRCP/2.0 1561 RECOGNITION-COMPLETE 1 COMPLETE
Channel-Identifier: [omitted]@[omitted]
Completion-Cause: 000 success
Content-Type: application/x-nlsml
Content-Length: 1374

<?xml version='1.0'?>
<result>
<interpretation [omitted]>
    <instance>
    one two three four five six seven eight nine one two three four five six seven eight nine one two three four five six seven eight nine one two three four five six seven eight nine one two three four five six seven eight nine one two three four five six seven eight nine one two three four five six seven eight nine one two three four five six seven eight nine one two three four five six seven eight nine one two three four five six one eight nine one two three four five six seven eight nine one two three four five six seven eight nine one two three four five six seven eight nine
    </instance>
    <input mode="speech">
    one two three four five six seven eight nine one two three four five six seven eight 

2024-10-25 14:02:10:715821 [INFO]   Send MRCPv2 Data [omitted]:[omitted] <-> [omitted]:[omitted] [539 bytes]
nine one two three four five six seven eight nine one two three four five six seven eight nine one two three four five six seven eight nine one two three four five six seven eight nine one two three four five six seven eight nine one two three four five six seven eight nine one two three four five six seven eight nine one two three four five six one eight nine one two three four five six seven eight nine one two three four five six seven eight nine one two three four five six seven eight nine
    </input>
</interpretation>
</result>
```

Here we can see the message was split into two chunks, a first chunk of 1022 bytes including the header, content length, and the first portion of the data - this is followed by a second message, containing the remaining data.

When this happens, the application process using this library reaches 100% CPU usage and becomes unresponsive, with us trapped in [the `while` loop in `mrcp_socket:_onReadable`](https://github.com/MayamaTakeshi/mrcp/blob/2250926fa39269e8371de3bc16eb053fed619e96/src/mrcp_socket.js#L82).

Then, within [`mrcp_socket.js`](https://github.com/MayamaTakeshi/mrcp/blob/2250926fa39269e8371de3bc16eb053fed619e96/src/mrcp_socket.js): 

[Line 85](https://github.com/MayamaTakeshi/mrcp/blob/2250926fa39269e8371de3bc16eb053fed619e96/src/mrcp_socket.js#L85) reads the header of the first message, e.g. in the example above the first 32 bytes of the 1022 we received for our first message.

[Line 90](https://github.com/MayamaTakeshi/mrcp/blob/2250926fa39269e8371de3bc16eb053fed619e96/src/mrcp_socket.js#L90) parses the header and retrieves the overall message length from the content-length header, returning us `1374`.

[Line 107](https://github.com/MayamaTakeshi/mrcp/blob/2250926fa39269e8371de3bc16eb053fed619e96/src/mrcp_socket.js#L90) attempts to read the remaining content of the message, e.g. in this case effectively calling `this._socket.read(1374 - 32))` (i.e. `this._socket.read(1342)`).

_However_ the socket's buffer only contains the first 1022 bytes from the _first message_, and none of the content from the second message.

This can be demonstrated by adding e.g. the following to the top of the `while` block (above comment on line 83):

```javascript
const entireBuffer = this._socket.read();

if (entireBuffer && entireBuffer.length) {
    // e.g. Logs 1022
    console.log('Current entire buffer length', entireBuffer.length);
    // Return the content we just read to not interfere with the upcoming code
    this._socket.unshift(entireBuffer);
}
```

---

I'm aware this _can_ be handled in the corresponding MRCP server, in this case [`unimrcp`](https://github.com/unispeech/unimrcp) by modifying its config to not split messages in this fashion (for reference if anyone ends up here it's modifying parameters `rx-buffer-size` and `tx-buffer-size` in `unimrcpserver.xml`), however it feels like the library should be resilient to crashes when this occurs?

If you agree library should handle this, and have any opinions on preferred resolution I'm happy to help if I can, just let me know 👍

Cheers!

**Comment by MayamaTakeshi** [comment]
Hi,  I am trying to reproduce this.
I created this server: https://github.com/MayamaTakeshi/mrcp/blob/master/samples/fragmenting_server.js
and this client:
https://github.com/MayamaTakeshi/mrcp/blob/master/samples/client_single_request.js
But the issue didn't happen. Here is output of ngrep showing the event packet from the server was fragmented:
```
takeshi@takeshi-desktop:mrcp$ sudo ngrep -d any -W byline -q . 'src port 9000'
interface: any
filter: ( src port 9000 ) and (ip || ip6)
match (JIT): .

T 127.0.0.1:9000 -> 127.0.0.1:60416 [AP] #3
MRCP/2.0 83 1 200 IN-PROGRESS.
channel-identifier: AB32AECB23433801@speechrecog.
.


T 127.0.0.1:9000 -> 127.0.0.1:60416 [AP] #4
MRCP/2.0 1561 RECOGNITION-COMPLETE 1 COMPLETE.
channel-identifier: AB32AECB23433801@speechrecog.
completion-cause: 000 success.
content-type: application/x-nlsml.
content-length: 1374.
.
<?xml version='1.0'?>
<result>
<interpretation 01234567789123456790123456789012345679012345678901234>
    <instance>
    one two three four five six seven eight nine one two three four five six seven eight nine one two three four five six seven eight nine one two three four five six seven eight nine one two three four five six seven eight nine one two three four five six seven eight nine one two three four five six seven eight nine one two three four five six seven eight nine one two three four five six seven eight nine one two three four five six one eight nine one two three four five six seven eight nine one two three four five six seven eight nine one two three four five six seven eight nine
    </instance>
    <input mode="speech">
    one two three four five six seven eight nine one two three four five six seven eight 

T 127.0.0.1:9000 -> 127.0.0.1:60416 [AP] #5
nine one two three four five six seven eight nine one two three four five six seven eight nine one two three four five six seven eight nine one two three four five six seven eight nine one two three four five six seven eight nine one two three four five six seven eight nine one two three four five six seven eight nine one two three four five six one eight nine one two three four five six seven eight nine one two three four five six seven eight nine one two three four five six seven eight nine
    </input>
</interpretation>
</result>

```
Here is the output of the client:
```
takeshi@takeshi-desktop:mrcp$ node samples/client_single_request.js 
Sending MRCP requests. result:  true
***********************************************
on data:
{
  type: 'response',
  version: '2.0',
  request_id: 1,
  status_code: 200,
  request_state: 'IN-PROGRESS',
  headers: { 'channel-identifier': 'AB32AECB23433801@speechrecog' }
}

***********************************************
on data:
{
  type: 'event',
  version: '2.0',
  event_name: 'RECOGNITION-COMPLETE',
  request_id: 1,
  request_state: 'COMPLETE',
  headers: {
    'channel-identifier': 'AB32AECB23433801@speechrecog',
    'completion-cause': '000 success',
    'content-type': 'application/x-nlsml',
    'content-length': '1374'
  },
  body: "<?xml version='1.0'?>\n" +
    '<result>\n' +
    '<interpretation 01234567789123456790123456789012345679012345678901234>\n' +
    '    <instance>\n' +
    '    one two three four five six seven eight nine one two three four five six seven eight nine one two three four five six seven eight nine one two three four five six seven eight nine one two three four five six seven eight nine one two three four five six seven eight nine one two three four five six seven eight nine one two three four five six seven eight nine one two three four five six seven eight nine one two three four five six one eight nine one two three four five six seven eight nine one two three four five six seven eight nine one two three four five six seven eight nine\n' +
    '    </instance>\n' +
    '    <input mode="speech">\n' +
    '    one two three four five six seven eight nine one two three four five six seven eight nine one two three four five six seven eight nine one two three four five six seven eight nine one two three four five six seven eight nine one two three four five six seven eight nine one two three four five six seven eight nine one two three four five six seven eight nine one two three four five six seven eight nine one two three four five six one eight nine one two three four five six seven eight nine one two three four five six seven eight nine one two three four five six seven eight nine\n' +
    '    </input>\n' +
    '</interpretation>\n' +
    '</result>\n'
}

```
Maybe there is something specific in the message that comes from unimrcp that is triggering the problem.
Could you try using a server script with the exact message from unimrcp to see if you can recreate the issue?
Also, maybe use ngrep to see if there is any garbage or extra packet coming from unimrcp (or maybe the second part of the message is not arriving).

**Comment by MayamaTakeshi** [comment]
Changing fragmenting_server.js to not send the secondPart of the message reproduces the 100% CPU usage issue.
I have changed the code to keep a buffer for reading partials (3edb03fab5d6d4e470bf7e3fdddf86cf41e0d07d)
It was published as v. 1.4.2.

**Comment by jsau-** [comment]
I'll try sneak some time over the weekend to test this new release and let you know how it goes - thanks so much for the quick turnaround on it! 👍

**Comment by jsau-** [comment]
New release has resolved, thanks so much @MayamaTakeshi 👍
